
omnissa:
  client:
    clientId: webapp.samples.omnissa.com
    clientSecret: Gp4mGG5klyCm8k3UZwJR4o2fCL4OqwBIplRl4yvAE90MVyRg
    accessTokenUri: https://dev.omnissaidentity.asia/SAAS/auth/oauthtoken
    userAuthorizationUri: https://dev.omnissaidentity.asia/SAAS/auth/oauth2/authorize
    authenticationScheme: header
    clientAuthenticationScheme: header
    scope: openid
  resource:
    userInfoUri: https://dev.omnissaidentity.asia/SAAS/jersey/manager/api/userinfo


logging:
  level:
    org.springframework.security: DEBUG
